# Generated by Django 2.2.5 on 2019-10-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191003_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sex',
            field=models.CharField(choices=[('man', 'Мужской'), ('women', 'Женский')], default='man', max_length=5),
        ),
    ]
