# Generated by Django 2.2.5 on 2019-10-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='static/images/users/default_logo.png', upload_to='static/images/users', verbose_name='Аватар'),
        ),
    ]
